doctrine:
    dbal:
        # Connexion à la base de données via l'URL d'environnement
        url: '%env(resolve:DATABASE_URL)%'
        
        # IMPORTANT : configurez la version de votre serveur de base de données
        server_version: '13' # Ajustez selon votre base de données

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity

        # Désactivation de l'auto_mapping pour éviter les messages de dépréciation
        controller_resolver:
            auto_mapping: false

        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
